### ISSUE TITLE
After upgrading Hue node server, I couldn't start Hue node server

### ISSUE THREAD

**Issue by pgattu** [exking/udi-hue-poly#3] opened 2019-12-30 22:12 UTC
I see the below error in the debug.log file:

```
12/30/2019, 2:06:44 PM - info: Hue(2): Processing command: start
12/30/2019, 2:06:44 PM - info: NS: Starting Local NodeServer Hue profile number 2 :: Version 0.1.10
12/30/2019, 2:06:44 PM - error: NSChild STDERR: Hue:   File "./hue.py", line 219
    LOGGER.debug(f"Hub {hub_idx} {data['type']} {name} {scene_data['type']} {scene_idx}:{scene_id}:{scene_data['name']}")
                                                                                                                       ^
SyntaxError: invalid syntax

12/30/2019, 2:06:44 PM - info: Hue(2): NodeServer Disconnected.
12/30/2019, 2:06:44 PM - info: Hue(2): n002_huebridge ST set sucessfully to 0 : UOM 2

```
I edited the "hue.py" file and removed the extra "f" character in the LOGGER invocations.  After clearing the "f" character in line 219 of the code, the nodeserver startup failed with the same error in other calls to the LOGGER.  So, I fixed all of them.

After fixing the hue.py file, the startup failed in node due to invalid "f" character in "node_types.py" file.  So I fixed that file too and then I was able to startup.  Not sure what caused the "f" character in the LOGGER calls.

**Comment by exking** [comment] 2019-12-30 22:40
Duplicate of #4

**Closed as completed by exking** 2019-12-30 22:40 UTC

**Comment by pgattu** [comment] 2019-12-30 23:56
This is not a duplicate of issue #4 .  There seems to be a problem in the code and I am pointing it out, along with how I fixed it.

**Comment by exking** [comment] 2019-12-31 03:46
f is a new format of the text string that requires python 3.6, there is no problem with the code.
